import 'package:flutter/material.dart';
import 'package:fl_chart/fl_chart.dart';
import '../../viewmodels/ai_insights_viewmodel.dart';
import '../../models/insights_data.dart';

class AiInsightsScreen extends StatefulWidget {
  final VoidCallback? onNotificationTapped;
  final bool hasNotification;
  final VoidCallback? onRefreshTapped;

  const AiInsightsScreen({
    super.key,
    this.onNotificationTapped,
    this.hasNotification = false,
    this.onRefreshTapped,
  });

  @override
  State<AiInsightsScreen> createState() => _AiInsightsScreenState();
}

class _AiInsightsScreenState extends State<AiInsightsScreen> {
  final AiInsightsViewModel _viewModel = AiInsightsViewModel();
  InsightsData? _insights;
  bool _isLoading = false;
  String _topItemsFilter = 'Monthly';

  // New Dashboard Colors
  static const Color bgColor = Color(0xFFF9FAFB);
  static const Color cardBg = Colors.white;
  static const Color borderColor = Color(0xFFE5E7EB);
  static const Color textDark = Color(0xFF111827);
  static const Color textMuted = Color(0xFF6B7280);
  
  static const Color primaryGreen = Color(0xFF4ADE80); 
  static const Color primaryGreenDark = Color(0xFF22C55E); 
  static const Color targetGrey = Color(0xFFF3F4F6); 
  static const Color redColor = Color(0xFFEF4444);

  @override
  void initState() {
    super.initState();
    _generateInsights();
  }

  Future<void> _generateInsights() async {
    setState(() {
      _isLoading = true;
      _insights = null;
    });
    final result = await _viewModel.generateInsights();
    if (mounted) {
      setState(() {
        _insights = result;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: bgColor,
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Container(
              padding: const EdgeInsets.fromLTRB(24, 20, 24, 8),
              color: Colors.transparent,
              child: Row(
                children: [
                  const Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Business Insights',
                          style: TextStyle(
                            fontSize: 22,
                            fontWeight: FontWeight.w700,
                            color: textDark,
                          ),
                        ),
                        SizedBox(height: 4),
                        Text(
                          'Insights generated by Gemini AI from your sales and inventory data.',
                          style: TextStyle(
                            fontSize: 14,
                            color: textMuted,
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 16),
                  const SizedBox(width: 16),
                  Row(
                    children: [
                      Container(
                        height: 40,
                        width: 40,
                        decoration: BoxDecoration(
                          color: Colors.white,
                          border: Border.all(color: const Color(0xFFE2E8F0)),
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Material(
                          color: Colors.transparent,
                          child: IconButton(
                            onPressed: widget.onNotificationTapped,
                            tooltip: "Notifications",
                            icon: Icon(
                              widget.hasNotification
                                  ? Icons.notifications_active_rounded
                                  : Icons.notifications_none_rounded,
                              size: 20,
                            ),
                            color: const Color(0xFF64748B),
                            padding: EdgeInsets.zero,
                            constraints: const BoxConstraints(),
                            splashRadius: 20,
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Container(
                        height: 40,
                        width: 40,
                        decoration: BoxDecoration(
                          color: Colors.white,
                          border: Border.all(color: const Color(0xFFE2E8F0)),
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Material(
                          color: Colors.transparent,
                          child: IconButton(
                            onPressed: () {
                              if (widget.onRefreshTapped != null) {
                                widget.onRefreshTapped!();
                              } else {
                                _generateInsights();
                              }
                            },
                            tooltip: "Refresh",
                            icon: const Icon(Icons.refresh_rounded, size: 20),
                            color: const Color(0xFF64748B),
                            padding: EdgeInsets.zero,
                            constraints: const BoxConstraints(),
                            splashRadius: 20,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Expanded(
              child: _isLoading
                  ? const Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          CircularProgressIndicator(color: primaryGreenDark),
                          SizedBox(height: 20),
                          Text('Analyzing business data...', style: TextStyle(color: textMuted, fontWeight: FontWeight.w500)),
                        ],
                      ),
                    )
                  : _insights == null
                      ? const Center(child: Text('No data yet.', style: TextStyle(color: textMuted)))
                      : SingleChildScrollView(
                          padding: const EdgeInsets.fromLTRB(24, 12, 24, 24),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.stretch,
                            children: [
                              // Row 1: KPI Cards
                              LayoutBuilder(
                                builder: (context, constraints) {
                                  if (constraints.maxWidth > 900) {
                                    return Row(
                                      children: [
                                        Expanded(child: _buildKpiCard('Total Revenue', 'RM ${_insights!.totalRevenue.toStringAsFixed(2)}', -12.4)),
                                        const SizedBox(width: 16),
                                        Expanded(child: _buildKpiCard('Total Orders', '${_insights!.totalTransactions}', 5.2)),
                                        const SizedBox(width: 16),
                                        Expanded(child: _buildKpiCard('Avg Order Value', 'RM ${_insights!.avgOrderValue.toStringAsFixed(2)}', 1.0)),
                                        const SizedBox(width: 16),
                                        Expanded(child: _buildKpiCard('Health Score', '${_insights!.healthScore}/100', _insights!.healthScore > 70 ? 10.0 : -5.0)),
                                      ],
                                    );
                                  } else {
                                    // Mobile/Tablet friendly wrap
                                    return Wrap(
                                      spacing: 16,
                                      runSpacing: 16,
                                      children: [
                                        SizedBox(width: (constraints.maxWidth / 2) - 8, child: _buildKpiCard('Total Revenue', 'RM ${_insights!.totalRevenue.toStringAsFixed(2)}', -12.4)),
                                        SizedBox(width: (constraints.maxWidth / 2) - 8, child: _buildKpiCard('Total Orders', '${_insights!.totalTransactions}', 5.2)),
                                        SizedBox(width: (constraints.maxWidth / 2) - 8, child: _buildKpiCard('Avg Order Value', 'RM ${_insights!.avgOrderValue.toStringAsFixed(2)}', 1.0)),
                                        SizedBox(width: (constraints.maxWidth / 2) - 8, child: _buildKpiCard('Health Score', '${_insights!.healthScore}/100', 5.0)),
                                      ],
                                    );
                                  }
                                },
                              ),
                              
                              const SizedBox(height: 24),
      
                              // Row 2: Sales Overview Chart & AI Report
                              LayoutBuilder(
                                builder: (context, constraints) {
                                  if (constraints.maxWidth > 900) {
                                    return Row(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Expanded(flex: 7, child: _buildSalesOverviewChart(_insights!)),
                                        const SizedBox(width: 24),
                                        Expanded(flex: 4, child: _buildAiReportCard(_insights!)),
                                      ],
                                    );
                                  }
                                  return Column(
                                    children: [
                                      _buildSalesOverviewChart(_insights!),
                                      const SizedBox(height: 24),
                                      _buildAiReportCard(_insights!),
                                    ],
                                  );
                                },
                              ),
      
                              const SizedBox(height: 24),
      
                              // Row 3: Top Items Sold & Urgent Restocks
                              LayoutBuilder(
                                builder: (context, constraints) {
                                  if (constraints.maxWidth > 900) {
                                    return Row(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Expanded(flex: 7, child: _buildTopItemsTable(_insights!)),
                                        const SizedBox(width: 24),
                                        Expanded(flex: 4, child: _buildUrgentRestocks(_insights!)),
                                      ],
                                    );
                                  }
                                  return Column(
                                    children: [
                                      _buildTopItemsTable(_insights!),
                                      const SizedBox(height: 24),
                                      _buildUrgentRestocks(_insights!),
                                    ],
                                  );
                                },
                              ),
                              const SizedBox(height: 40),
                            ],
                          ),
                        ),
            ),
          ],
        ),
      ),
    );
  }

  // ── KPI Card ──────────────────────────────────────────────────────────────
  Widget _buildKpiCard(String title, String value, double mockPercentage) {
    bool isPositive = mockPercentage >= 0;
    
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(color: textDark, fontSize: 15, fontWeight: FontWeight.w600)),
          const SizedBox(height: 16),
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: FittedBox(
                  fit: BoxFit.scaleDown,
                  alignment: Alignment.centerLeft,
                  child: Text(value, style: const TextStyle(color: textDark, fontSize: 28, fontWeight: FontWeight.bold)),
                ),
              ),
              const SizedBox(width: 8),
              Flexible(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(isPositive ? Icons.arrow_upward : Icons.arrow_downward, color: isPositive ? primaryGreenDark : redColor, size: 14),
                        const SizedBox(width: 2),
                        Flexible(
                          child: Text(
                            '${mockPercentage.abs()}%',
                            style: TextStyle(color: isPositive ? primaryGreenDark : redColor, fontSize: 13, fontWeight: FontWeight.w600),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                    const FittedBox(
                      fit: BoxFit.scaleDown,
                      child: Text('From last week', style: TextStyle(color: textMuted, fontSize: 11)),
                    ),
                  ],
                ),
              )
            ],
          ),
        ],
      ),
    );
  }

  // ── Sales Overview Bar Chart ──────────────────────────────────────────────
  Widget _buildSalesOverviewChart(InsightsData data) {
    List<BarChartGroupData> barGroups = [];
    double maxY = 0;
    
    for (int i = 0; i < 6; i++) {
      double rev = 0;
      for (int j = 0; j < 5; j++) {
        int index = (i * 5) + j;
        if (index < data.dailyRevenues.length) rev += data.dailyRevenues[index];
      }
      if (rev > maxY) maxY = rev;
      
      double target = rev * 1.3; 
      if (target > maxY) maxY = target;

      barGroups.add(
        BarChartGroupData(
          x: i,
          barRods: [
            BarChartRodData(
              toY: target == 0 ? 10 : target,
              color: targetGrey,
              width: 12,
              borderRadius: BorderRadius.circular(4),
            ),
            BarChartRodData(
              toY: rev,
              color: primaryGreen,
              width: 12,
              borderRadius: BorderRadius.circular(4),
            ),
          ],
        ),
      );
    }
    
    maxY = maxY == 0 ? 100 : maxY * 1.2;

    return Container(
      height: 400,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Flexible(child: Text('Sales Trend & Forecast', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: textDark))),
              Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  _buildLegendItem('Historical', targetGrey),
                  const SizedBox(width: 12),
                  _buildLegendItem('AI Predicted', primaryGreen),
                ],
              )
            ],
          ),
          const SizedBox(height: 12),
          Wrap(
            crossAxisAlignment: WrapCrossAlignment.center,
            spacing: 12,
            runSpacing: 8,
            children: [
              Text('RM ${data.totalRevenue.toStringAsFixed(2)}', style: const TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: textDark)),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(color: redColor, borderRadius: BorderRadius.circular(20)),
                child: const Text('-2.4%', style: TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold)),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                decoration: BoxDecoration(color: bgColor, borderRadius: BorderRadius.circular(20)),
                child: const Text('Last 30 Days', style: TextStyle(color: textDark, fontSize: 13, fontWeight: FontWeight.w600)),
              )
            ],
          ),
          const SizedBox(height: 40),
          Expanded(
            child: BarChart(
              BarChartData(
                alignment: BarChartAlignment.spaceAround,
                maxY: maxY,
                barTouchData: BarTouchData(enabled: false),
                titlesData: FlTitlesData(
                  show: true,
                  bottomTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      getTitlesWidget: (value, meta) {
                        List<String> labels = ['W1', 'W2', 'W3', 'W4', 'W5', 'W6'];
                        return Padding(
                          padding: const EdgeInsets.only(top: 10.0),
                          child: Text(labels[value.toInt()], style: const TextStyle(color: textMuted, fontSize: 12, fontWeight: FontWeight.w500)),
                        );
                      },
                    ),
                  ),
                  leftTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      reservedSize: 50,
                      interval: maxY / 4 == 0 ? 1 : maxY / 4,
                      getTitlesWidget: (value, meta) {
                        if (value == 0) return const Text('RM 0', style: TextStyle(color: textMuted, fontSize: 12));
                        if (value == maxY) return const SizedBox.shrink();
                        return Text('RM ${(value/1000).toStringAsFixed(1)}k', style: const TextStyle(color: textMuted, fontSize: 12));
                      },
                    ),
                  ),
                  topTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  rightTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false)),
                ),
                gridData: FlGridData(show: false),
                borderData: FlBorderData(show: false),
                barGroups: barGroups,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLegendItem(String label, Color color) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Container(width: 8, height: 8, decoration: BoxDecoration(color: color, shape: BoxShape.circle)),
        const SizedBox(width: 6),
        Text(label, style: const TextStyle(color: textMuted, fontSize: 13, fontWeight: FontWeight.w600)),
      ],
    );
  }

  // ── AI Report Card ────────────────────────────────────────────────────────
  Widget _buildAiReportCard(InsightsData data) {
    return Container(
      height: 400,
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.all(24),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Flexible(child: Text('AI Consultant Report', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: textDark))),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(color: bgColor, borderRadius: BorderRadius.circular(16)),
                  child: const Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.auto_awesome, color: primaryGreenDark, size: 14),
                      SizedBox(width: 4),
                      Text('Gemini', style: TextStyle(color: textDark, fontSize: 12, fontWeight: FontWeight.w600)),
                    ],
                  ),
                )
              ],
            ),
          ),
          Expanded(
            child: data.aiTimeline == null || data.aiTimeline!.isEmpty
                ? const Center(child: Text('No timeline data available.', style: TextStyle(color: textMuted)))
                : _TimelineScrollSync(items: data.aiTimeline!),
          ),
        ],
      ),
    );
  }

  // ── Top Items Sold Table ──────────────────────────────────────────────────
  Widget _buildTopItemsTable(InsightsData data) {
    List<TopProduct> currentList = data.topProducts;
    if (_topItemsFilter == 'Weekly') currentList = data.topProductsWeekly;
    if (_topItemsFilter == 'Yearly') currentList = data.topProductsYearly;

    return Container(
      height: 350,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Flexible(child: Text('Top Items Sold', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: textDark))),
              PopupMenuButton<String>(
                onSelected: (value) {
                  setState(() {
                    _topItemsFilter = value;
                  });
                },
                offset: const Offset(0, 40),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                itemBuilder: (context) => [
                  const PopupMenuItem(value: 'Weekly', child: Text('Weekly')),
                  const PopupMenuItem(value: 'Monthly', child: Text('Monthly')),
                  const PopupMenuItem(value: 'Yearly', child: Text('Yearly')),
                ],
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  decoration: BoxDecoration(color: bgColor, borderRadius: BorderRadius.circular(20)),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(_topItemsFilter, style: const TextStyle(color: textDark, fontSize: 13, fontWeight: FontWeight.w600)),
                      const SizedBox(width: 4),
                      const Icon(Icons.keyboard_arrow_down, size: 16, color: textMuted),
                    ],
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Text('${currentList.length} Products', style: const TextStyle(color: textMuted, fontSize: 14, fontWeight: FontWeight.w500)),
              Container(
                width: 250,
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: BoxDecoration(color: bgColor, borderRadius: BorderRadius.circular(24)),
                child: const Row(
                  children: [
                    Icon(Icons.search, color: textMuted, size: 18),
                    SizedBox(width: 8),
                    Text('Search Items', style: TextStyle(color: textMuted, fontSize: 13)),
                  ],
                ),
              )
            ],
          ),
          const SizedBox(height: 24),
          // Table Header
          const Row(
            children: [
              SizedBox(width: 40, child: Text('#', style: TextStyle(color: textMuted, fontSize: 12, fontWeight: FontWeight.w600))),
              Expanded(flex: 3, child: Text('Product Name', style: TextStyle(color: textMuted, fontSize: 12, fontWeight: FontWeight.w600))),
              Expanded(flex: 2, child: Text('Qty Sold', textAlign: TextAlign.center, style: TextStyle(color: textMuted, fontSize: 12, fontWeight: FontWeight.w600))),
              Expanded(flex: 2, child: Text('Total Revenue', textAlign: TextAlign.right, style: TextStyle(color: textMuted, fontSize: 12, fontWeight: FontWeight.w600))),
            ],
          ),
          const SizedBox(height: 8),
          const Divider(color: borderColor),
          // Table Rows
          Expanded(
            child: currentList.isEmpty
                ? const Center(child: Text('No sales recorded.', style: TextStyle(color: textMuted)))
                : ListView.builder(
                    itemCount: currentList.length,
                    itemBuilder: (context, index) {
                      final item = currentList[index];
                      return Padding(
                        padding: const EdgeInsets.symmetric(vertical: 12.0),
                        child: Row(
                          children: [
                            SizedBox(width: 40, child: Text('${index + 1}', style: const TextStyle(color: textMuted, fontSize: 14, fontWeight: FontWeight.w600))),
                            Expanded(flex: 3, child: Text(item.name, overflow: TextOverflow.ellipsis, style: const TextStyle(color: textDark, fontSize: 14, fontWeight: FontWeight.w600))),
                            Expanded(flex: 2, child: Text('${item.unitsSold}', textAlign: TextAlign.center, style: const TextStyle(color: textDark, fontSize: 14))),
                            Expanded(
                              flex: 2, 
                              child: Text(
                                'RM ${item.revenue.toStringAsFixed(2)}', 
                                textAlign: TextAlign.right, 
                                overflow: TextOverflow.ellipsis,
                                style: const TextStyle(color: Color(0xFF22C55E), fontSize: 14, fontWeight: FontWeight.w700)
                              )
                            ),
                          ],
                        ),
                      );
                    },
                  ),
          )
        ],
      ),
    );
  }

  // ── Urgent Restocks ───────────────────────────────────────────────────────
  Widget _buildUrgentRestocks(InsightsData data) {
    return Container(
      height: 350,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Inventory Alerts', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: textDark)),
          const SizedBox(height: 6),
          const Text('Urgent Restocks Needed', style: TextStyle(color: textMuted, fontSize: 13)),
          const SizedBox(height: 24),
          Expanded(
            child: data.urgentRestocks.isEmpty
                ? const Center(child: Text('All stock levels are healthy.', style: TextStyle(color: textMuted)))
                : ListView.builder(
                    itemCount: data.urgentRestocks.length,
                    itemBuilder: (context, index) {
                      final item = data.urgentRestocks[index];
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 20.0),
                        child: Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.all(10),
                              decoration: BoxDecoration(color: redColor.withOpacity(0.1), borderRadius: BorderRadius.circular(8)),
                              child: const Icon(Icons.warning_amber_rounded, color: redColor, size: 20),
                            ),
                            const SizedBox(width: 16),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(item.name, overflow: TextOverflow.ellipsis, style: const TextStyle(color: textDark, fontSize: 14, fontWeight: FontWeight.w600)),
                                  const SizedBox(height: 4),
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(4),
                                    child: const LinearProgressIndicator(
                                      value: 0.1, 
                                      backgroundColor: targetGrey,
                                      color: redColor,
                                      minHeight: 6,
                                    ),
                                  )
                                ],
                              ),
                            ),
                            const SizedBox(width: 16),
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.end,
                              children: [
                                Text('${item.stock} left', style: const TextStyle(color: textDark, fontSize: 14, fontWeight: FontWeight.w600)),
                                Text('${item.daysLeft} days', style: const TextStyle(color: textMuted, fontSize: 12)),
                              ],
                            )
                          ],
                        ),
                      );
                    },
                  ),
          )
        ],
      ),
    );
  }
}

class _TimelineScrollSync extends StatefulWidget {
  final List<Map<String, dynamic>> items;
  const _TimelineScrollSync({required this.items});

  @override
  State<_TimelineScrollSync> createState() => _TimelineScrollSyncState();
}

class _TimelineScrollSyncState extends State<_TimelineScrollSync> {
  final ScrollController _scrollController = ScrollController();
  double _scrollProgress = 0.0;
  
  static const Color textDark = Color(0xFF111827);
  static const Color textMuted = Color(0xFF6B7280);

  final GlobalKey _greenLineKey = GlobalKey();
  late List<GlobalKey> _itemKeys;
  late List<bool> _isReached;

  @override
  void initState() {
    super.initState();
    _itemKeys = List.generate(widget.items.length, (index) => GlobalKey());
    _isReached = List.generate(widget.items.length, (index) => index == 0);

    _scrollController.addListener(() {
      if (_scrollController.position.maxScrollExtent > 0) {
        setState(() {
          _scrollProgress = (_scrollController.offset / _scrollController.position.maxScrollExtent).clamp(0.0, 1.0);
          _checkIntersections();
        });
      }
    });

    WidgetsBinding.instance.addPostFrameCallback((_) {
      setState(() {
        _checkIntersections();
      });
    });
  }

  void _checkIntersections() {
    if (_greenLineKey.currentContext == null) return;
    final greenBox = _greenLineKey.currentContext!.findRenderObject() as RenderBox?;
    if (greenBox == null) return;
    
    // Absolute Y position of the tip of the green line
    double greenTipY = greenBox.localToGlobal(Offset(0, greenBox.size.height)).dy;

    for (int i = 1; i < widget.items.length; i++) {
      final itemContext = _itemKeys[i].currentContext;
      if (itemContext != null) {
        final itemBox = itemContext.findRenderObject() as RenderBox?;
        if (itemBox != null) {
          // Center of the 32x32 icon container
          double itemCenterY = itemBox.localToGlobal(const Offset(0, 16)).dy;
          _isReached[i] = greenTipY >= itemCenterY || _scrollProgress >= 0.99;
        }
      }
    }
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  IconData _getIcon(String iconName) {
    switch (iconName) {
      case 'chart': return Icons.bar_chart_rounded;
      case 'trending_up': return Icons.trending_up_rounded;
      case 'inventory_2': return Icons.inventory_2_rounded;
      case 'lightbulb': return Icons.lightbulb_outline_rounded;
      default: return Icons.circle;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        // The background timeline line
        Positioned(
          left: 38.5,
          top: 24,
          bottom: 24,
          child: Container(
            width: 3,
            color: Colors.grey.shade200,
          ),
        ),
        // The dynamic green timeline line that fills on scroll
        Positioned(
          left: 38.5,
          top: 24,
          bottom: 24,
          child: LayoutBuilder(
            builder: (context, constraints) {
              return Column(
                children: [
                  Container(
                    key: _greenLineKey,
                    width: 3,
                    height: constraints.maxHeight * _scrollProgress,
                    color: const Color(0xFF059669),
                  ),
                ],
              );
            }
          ),
        ),
        SingleChildScrollView(
          controller: _scrollController,
          padding: const EdgeInsets.only(left: 24, right: 24, top: 24, bottom: 40),
          child: Column(
            children: List.generate(widget.items.length, (index) {
              final item = widget.items[index];
              bool isReached = _isReached.length > index ? _isReached[index] : false;

              return Padding(
                padding: const EdgeInsets.only(bottom: 32.0),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Icon Node
                    Container(
                      key: _itemKeys.length > index ? _itemKeys[index] : null,
                      width: 32,
                      height: 32,
                      decoration: BoxDecoration(
                        color: isReached ? const Color(0xFFD1FAE5) : Colors.white,
                        shape: BoxShape.circle,
                        border: Border.all(
                          color: isReached ? const Color(0xFF059669) : Colors.grey.shade300,
                          width: 2,
                        ),
                      ),
                      child: Icon(
                        _getIcon(item['icon']),
                        color: isReached ? const Color(0xFF059669) : Colors.grey.shade400,
                        size: 16,
                      ),
                    ),
                    const SizedBox(width: 16),
                    // Text Content
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            item['title'],
                            style: TextStyle(
                              color: isReached ? textDark : textMuted,
                              fontSize: 15,
                              fontWeight: isReached ? FontWeight.w700 : FontWeight.w600,
                            ),
                          ),
                          const SizedBox(height: 6),
                          Text(
                            item['content'],
                            style: const TextStyle(color: textMuted, height: 1.5, fontSize: 14),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              );
            }),
          ),
        ),
      ],
    );
  }
}
